In [3]:
import pandas as pd

# Hek293t m6ace-seq ground truth

## This file was from the author of the m6ace-seq

In [4]:
raw_hek293t_df = pd.read_excel('hek293t_m6ace/m6ace_hek293t_fromAuthor.xlsx')
raw_hek293t_df['Chr']=raw_hek293t_df['Chr'].str.replace('chr','')
raw_hek293t_df['WT RML average'] = raw_hek293t_df.loc[:,['WT rep1 RML', 'WT rep2 RML','WT rep3 RML']].mean(axis=1)
raw_hek293t_df['Mettl3-KO RML average'] = raw_hek293t_df.loc[:,['Mettl3-KO rep1 RML', 'Mettl3-KO rep2 RML','Mettl3-KO rep3 RML']].mean(axis=1)
raw_hek293t_df['WT-KO'] = raw_hek293t_df['WT RML average']/raw_hek293t_df['Mettl3-KO RML average']
raw_hek293t_df['mettl3-m6a'] = 0
raw_hek293t_df.loc[raw_hek293t_df['WT-KO'] >=4,'mettl3-m6a'] = 1
raw_hek293t_df.head()

,Chr,Start,End,Strand,WT rep1 RML,WT rep2 RML,WT rep3 RML,Mettl3-KO rep1 RML,Mettl3-KO rep2 RML,Mettl3-KO rep3 RML,Gene,Annotation,Motif,WT DESeq2 padj,Mettl3-KO DESeq2 padj,WT RML average,Mettl3-KO RML average,WT-KO,mettl3-m6a
0,1,110347553,110347554,+,2.642931,5.642169,0.000000,0.0,0.0,0.0,NaN,unannotated,GAACA,0.01580,NaN,2.761700,0.0,inf,1
1,1,110347674,110347675,+,9.250258,4.048256,12.375419,0.0,0.0,0.0,NaN,unannotated,AAACT,0.01670,NaN,8.557978,0.0,inf,1
2,1,12019469,12019470,+,6.815979,14.218266,7.734637,0.0,0.0,0.0,MIIP,5utr,CCAAT,0.01500,0.00192,9.589627,0.0,inf,1
3,1,201829159,201829160,+,4.868557,16.587977,0.000000,0.0,0.0,0.0,IPO9,5utr,TCATT,0.00588,0.01798,7.152178,0.0,inf,1
4,1,230642480,230642481,+,10.710825,7.109133,20.110056,0.0,0.0,0.0,COG2,5utr,CCATG,0.01430,0.000137,12.643338,0.0,inf,1

## This is from the m6anet paper

In [5]:
m6anet_hek293t_df = pd.read_csv('hek293t_m6ace/m6ace_hek293t_fromm6anet.csv')
print(m6anet_hek293t_df.shape)
m6anet_hek293t_df.head()

(15790, 9)

,gene_id,genomic_position,transcript_id,transcript_position,HCT116_model,n_reads,y_true,HEK293T_model,Arabidopsis_model
0,ENSG00000224032,112161038,ENST00000413221,512,0.190810,63,False,0.348991,0.012517
1,ENSG00000224032,112161186,ENST00000413221,660,0.520088,61,True,0.627325,0.472298
2,ENSG00000224032,112161190,ENST00000413221,664,0.816225,56,True,0.829118,0.771490
3,ENSG00000224032,112161222,ENST00000413221,696,0.093021,58,False,0.225244,0.086567
4,ENSG00000224032,112161729,ENST00000413221,796,0.158405,64,False,0.365427,0.037362

## This is from the xpore zenodo 

[link](https://zenodo.org/records/5707193)

In [6]:
xpore_hek293t_df = pd.read_csv('hek293t_m6ace/m6ace_hek293t_fromxPore.csv')
xpore_hek293t_df['Chr']=xpore_hek293t_df['Chr'].str.replace('chr','')
xpore_hek293t_df.head()

,Chr,Start,End,Strand,WT-RML1,WT-RML2,WT-RML3,KO-RML1,KO-RML2,KO-RML3,Gene,Type,Motif,padj-WT,padj-KO,WT-RML-avg,KO-RML-avg,WT-KO,pval
0,X,136874122,136874123,-,1.110942,1.305861,0.939316,0.156518,0.145244,0.067597,RBMX,3utr,GGACC,7.370000e-12,NaN,1.118706,0.123119,9.086362,0.000406
1,6,21596201,21596202,+,5.263748,9.538153,3.859584,0.801101,1.026481,0.657681,SOX4,3utr,GGACG,2.690000e-06,0.041109,6.220495,0.828421,7.508860,0.017234
2,5,138164816,138164817,-,1.741822,1.270409,0.890673,0.104345,0.167589,0.106152,BRD8,cds,GGACT,7.329672e-03,NaN,1.300968,0.126029,10.322805,0.004466
3,9,130135163,130135164,+,3.461313,1.184973,1.809622,0.112372,0.402213,0.265380,GPR107,3utr,TAACT,3.079585e-02,NaN,2.151969,0.259988,8.277183,0.025288
4,6,35455983,35455984,+,4.317337,5.767256,2.573056,0.486944,0.391040,0.796140,FANCE,cds,AGACA,1.720000e-05,NaN,4.219216,0.558041,7.560761,0.008547

## This is from the m6ace-seq paper supplementary data 4

In [7]:
m6aceseq_hek293t_df = pd.read_excel('hek293t_m6ace/m6ace_hek293t_fromPaper.xlsx')
m6aceseq_hek293t_df['Chr']=m6aceseq_hek293t_df['Chr'].str.replace('chr','')
m6aceseq_hek293t_df['WT RML average'] = m6aceseq_hek293t_df.loc[:,['WT rep1 RML', 'WT rep2 RML','WT rep3 RML']].mean(axis=1)
m6aceseq_hek293t_df['Mettl3-KO RML average'] = m6aceseq_hek293t_df.loc[:,['Mettl3-KO rep1 RML', 'Mettl3-KO rep2 RML','Mettl3-KO rep3 RML']].mean(axis=1)
m6aceseq_hek293t_df['WT-KO'] = m6aceseq_hek293t_df['WT RML average']/m6aceseq_hek293t_df['Mettl3-KO RML average']
m6aceseq_hek293t_df['mettl3-m6a'] = 0
m6aceseq_hek293t_df.loc[m6aceseq_hek293t_df['WT-KO'] >=4,'mettl3-m6a'] = 1
m6aceseq_hek293t_df.head()

,Chr,Start,End,Strand,WT rep1 RML,WT rep2 RML,WT rep3 RML,Mettl3-KO rep1 RML,Mettl3-KO rep2 RML,Mettl3-KO rep3 RML,Gene,Annotation,Motif,WT DESeq2 padj,Mettl3-KO DESeq2 padj,WT RML average,Mettl3-KO RML average,WT-KO,mettl3-m6a
0,X,136874122,136874123,-,1.110942,1.305861,0.939316,0.156518,0.145244,0.067597,RBMX,3utr,GGACC,7.369375e-12,NaN,1.118706,0.123119,9.086362,1
1,6,21596201,21596202,+,5.263748,9.538153,3.859584,0.801101,1.026481,0.657681,SOX4,3utr,GGACG,2.692322e-06,0.041109,6.220495,0.828421,7.508860,1
2,5,138164816,138164817,-,1.741822,1.270409,0.890673,0.104345,0.167589,0.106152,BRD8,cds,GGACT,7.329672e-03,NaN,1.300968,0.126029,10.322805,1
3,9,130135163,130135164,+,3.461313,1.184973,1.809622,0.112372,0.402213,0.265380,GPR107,3utr,TAACT,3.079585e-02,NaN,2.151969,0.259988,8.277183,1
4,6,35455983,35455984,+,4.317337,5.767256,2.573056,0.486944,0.391040,0.796140,FANCE,cds,AGACA,1.716855e-05,NaN,4.219216,0.558041,7.560761,1

In [8]:
print(xpore_hek293t_df.shape)
print(m6aceseq_hek293t_df.shape)
print(m6aceseq_hek293t_df.merge(xpore_hek293t_df,on=['Chr','Start','End','Strand'],how='outer').shape)

# So the supplementary file was the same one as the xpore one

(15073, 19)
(15073, 19)
(15073, 34)

But these sites are all positive sites

In [9]:
print(raw_hek293t_df.shape)
print(m6aceseq_hek293t_df.shape)

(48027, 19)
(15073, 19)

In [19]:
merged_hek293t_df = raw_hek293t_df.merge(m6aceseq_hek293t_df,on=['Chr','Start','End','Strand'],how='outer').loc[:,['Chr','Start','End','Strand',
                                                                                                                   'Motif_x','Motif_y','WT-KO_x',
                                                                                                                   'WT-KO_y','WT RML average_x',
                                                                                                                   'Mettl3-KO RML average_x','WT '
                                                                                                                                             'RML average_y','Mettl3-KO RML average_y','mettl3-m6a_x','mettl3-m6a_y']]
merged_hek293t_df['Motif'] = merged_hek293t_df['Motif_x']
merged_hek293t_df.head()

,Chr,Start,End,Strand,Motif_x,Motif_y,WT-KO_x,WT-KO_y,WT RML average_x,Mettl3-KO RML average_x,WT RML average_y,Mettl3-KO RML average_y,mettl3-m6a_x,mettl3-m6a_y,Motif
0,1,110347553,110347554,+,GAACA,GAACA,inf,9.29099,2.761700,0.0,4.524189,0.486944,1.0,1.0,GAACA
1,1,110347674,110347675,+,AAACT,NaN,inf,NaN,8.557978,0.0,NaN,NaN,1.0,NaN,AAACT
2,1,12019469,12019470,+,CCAAT,NaN,inf,NaN,9.589627,0.0,NaN,NaN,1.0,NaN,CCAAT
3,1,201829159,201829160,+,TCATT,NaN,inf,NaN,7.152178,0.0,NaN,NaN,1.0,NaN,TCATT
4,1,230642480,230642481,+,CCATG,NaN,inf,NaN,12.643338,0.0,NaN,NaN,1.0,NaN,CCATG

In [10]:
# merged_hek293t_df = raw_hek293t_df.merge(m6aceseq_hek293t_df,on=['Chr','Start','End','Strand'],how='outer').loc[:,['Chr','Start','End','Strand',
#                                                                                                                    'Motif_x','Motif_y','WT-KO_x',
#                                                                                                                    'WT-KO_y','WT RML average_x',
#                                                                                                                    'Mettl3-KO RML average_x','WT '
#                                                                                                                                              'RML average_y','Mettl3-KO RML average_y','mettl3-m6a_x','mettl3-m6a_y']]
# 
# merged_hek293t_df.loc[merged_hek293t_df['Motif_x'].isna(),'Motif'] = merged_hek293t_df.loc[merged_hek293t_df['Motif_x'].isna(),'Motif_y']

In [20]:
(merged_hek293t_df.loc[merged_hek293t_df['mettl3-m6a_x'] == merged_hek293t_df['mettl3-m6a_y'],['Chr','Start','End','Strand','Motif','mettl3-m6a_x']]
 .sort_values(['Chr','Start']).to_csv('hek293t_m6ace/m6ace_hek293t_GT_positive.csv',index=False,header=['Chr','Start','End','Strand','Motif',
                                                                                                    'mettl3-m6a']))

In [21]:
merged_hek293t_df.loc[(merged_hek293t_df['mettl3-m6a_y'].isna())&(merged_hek293t_df['mettl3-m6a_x']==0),['Chr','Start','End','Strand','Motif','mettl3-m6a_x']].sort_values(['Chr','Start']).to_csv('hek293t_m6ace/m6ace_hek293t_GT_negative.csv',index=False,header=['Chr','Start','End','Strand','Motif','mettl3-m6a'])

In [22]:
merged_hek293t_df.loc[((merged_hek293t_df['mettl3-m6a_y'].isna())&(merged_hek293t_df['mettl3-m6a_x']==0))|(merged_hek293t_df['mettl3-m6a_x'] == merged_hek293t_df['mettl3-m6a_y']),['Chr','Start','End','Strand','Motif','mettl3-m6a_x']].sort_values(['Chr','Start']).to_csv('hek293t_m6ace/m6ace_hek293t_GT.csv',index=False,header=['Chr','Start','End','Strand','Motif','mettl3-m6a'])

In [23]:
merged_hek293t_df['mettl3-m6a'] = merged_hek293t_df['mettl3-m6a_x']
merged_hek293t_df.loc[merged_hek293t_df['mettl3-m6a_x'].isna(),'mettl3-m6a'] = merged_hek293t_df.loc[merged_hek293t_df['mettl3-m6a_x'].isna(),'mettl3-m6a_y']
merged_hek293t_df.loc[~merged_hek293t_df['mettl3-m6a_y'].isna(),'mettl3-m6a'] = merged_hek293t_df.loc[~merged_hek293t_df['mettl3-m6a_y'].isna(),'mettl3-m6a_y']

In [25]:
# merged_hek293t_df.loc[:,['Chr','Start','End','Strand','Motif','mettl3-m6a']].sort_values(['Chr','Start']).to_csv('hek293t_m6ace/m6ace_hek293t_GT_extend.csv',index=False)
merged_hek293t_df

,Chr,Start,End,Strand,Motif_x,Motif_y,WT-KO_x,WT-KO_y,WT RML average_x,Mettl3-KO RML average_x,WT RML average_y,Mettl3-KO RML average_y,mettl3-m6a_x,mettl3-m6a_y,Motif,mettl3-m6a
0,1,110347553,110347554,+,GAACA,GAACA,inf,9.290990,2.761700,0.0,4.524189,0.486944,1.0,1.0,GAACA,1.0
1,1,110347674,110347675,+,AAACT,NaN,inf,NaN,8.557978,0.0,NaN,NaN,1.0,NaN,AAACT,1.0
2,1,12019469,12019470,+,CCAAT,NaN,inf,NaN,9.589627,0.0,NaN,NaN,1.0,NaN,CCAAT,1.0
3,1,201829159,201829160,+,TCATT,NaN,inf,NaN,7.152178,0.0,NaN,NaN,1.0,NaN,TCATT,1.0
4,1,230642480,230642481,+,CCATG,NaN,inf,NaN,12.643338,0.0,NaN,NaN,1.0,NaN,CCATG,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48797,7,55472772,55472773,-,NaN,GAACG,NaN,6.430808,NaN,NaN,1.426092,0.221759,NaN,1.0,NaN,1.0
48798,18,79903630,79903631,-,NaN,GGACA,NaN,9.711605,NaN,NaN,14.869536,1.531110,NaN,1.0,NaN,1.0
48799,6,109368849,109368850,-,NaN,AAACA,NaN,9.861309,NaN,NaN,0.942728,0.095599,NaN,1.0,NaN,1.0
48800,16,29807531,29807532,+,NaN,GGAGA,NaN,5.190338,NaN,NaN,4.629984,0.892039,NaN,1.0,NaN,1.0
48801,1,155610771,155610772,+,NaN,GGACT,NaN,7.434670,NaN,NaN,1.601358,0.215391,NaN,1.0,NaN,1.0

In [26]:
(merged_hek293t_df.loc[:,['Chr','Start','End','Strand','Motif','mettl3-m6a','WT-KO_x','WT-KO_y','WT RML average_x','WT RML average_y','Mettl3-KO '
                                                                                                                                      'RML average_x','Mettl3-KO RML average_y']]
 .sort_values(['Chr','Start']).to_csv
 ('hek293t_m6ace/m6ace_hek293t_GT_extend.csv',index=False))

# Manifest

- m6ace_hek293t_GT_positive.csv: positive sites in both xpore and latest result from the author
- m6ace_hek293t_GT_negative.csv: negative sites in both xpore and latest result from the author
- m6ace_hek293t_GT.csv: all sites in both xpore and latest result from the author
- m6ace_hek293t_GT_extend.csv: all sites in both  xpore and latest result from the author (positive sites from any of the two are positive sites)

In [15]:
merged_hek293t_df

,Chr,Start,End,Strand,Motif_x,Motif_y,WT-KO_x,WT-KO_y,mettl3-m6a_x,mettl3-m6a_y,Motif,mettl3-m6a
0,1,110347553,110347554,+,GAACA,GAACA,inf,9.290990,1.0,1.0,GAACA,1.0
1,1,110347674,110347675,+,AAACT,NaN,inf,NaN,1.0,NaN,AAACT,1.0
2,1,12019469,12019470,+,CCAAT,NaN,inf,NaN,1.0,NaN,CCAAT,1.0
3,1,201829159,201829160,+,TCATT,NaN,inf,NaN,1.0,NaN,TCATT,1.0
4,1,230642480,230642481,+,CCATG,NaN,inf,NaN,1.0,NaN,CCATG,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
48797,7,55472772,55472773,-,NaN,GAACG,NaN,6.430808,NaN,1.0,GAACG,1.0
48798,18,79903630,79903631,-,NaN,GGACA,NaN,9.711605,NaN,1.0,GGACA,1.0
48799,6,109368849,109368850,-,NaN,AAACA,NaN,9.861309,NaN,1.0,AAACA,1.0
48800,16,29807531,29807532,+,NaN,GGAGA,NaN,5.190338,NaN,1.0,GGAGA,1.0
48801,1,155610771,155610772,+,NaN,GGACT,NaN,7.434670,NaN,1.0,GGACT,1.0